DROP DATABASE IF EXISTS `myBI`;
CREATE DATABASE `myBI`; 
USE `myBI`;

CREATE TABLE myBI.FORNECEDOR(
    idFORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL
);

CREATE TABLE myBI.CATEGORIA(
    idCATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL
);

CREATE TABLE myBI.PRODUTO(
    idPRODUTO INT AUTO_INCREMENT PRIMARY KEY,
    PRODUTO VARCHAR(45) NOT NULL,
    VALOR DECIMAL(10,2),
    CUSTO_MEDIO DECIMAL(10,2),
    fkCATEGORIA INT,
    fkFORNECEDOR INT,
    FOREIGN KEY (fkFORNECEDOR) REFERENCES myBI.FORNECEDOR(idFORNECEDOR),
    FOREIGN KEY (fkCATEGORIA) REFERENCES myBI.CATEGORIA(idCATEGORIA)
);

CREATE TABLE myBI.CLIENTE(
    idCLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    SOBRENOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(45) UNIQUE NOT NULL,
    SEXO ENUM('m','f') NOT NULL,
    NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE myBI.ENDERECO(
    idENDERECO INT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(60) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL,
    REGIAO VARCHAR(45) NOT NULL,
    fkCLIENTE INT,  -- CLIENTE_idCLIENTE
    FOREIGN KEY (fkCLIENTE) REFERENCES myBI.CLIENTE(idCLIENTE)
);

CREATE TABLE myBI.FORMA_PAGAMENTO(
    idFORMA_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    METODO VARCHAR(45) NOT NULL
);

CREATE TABLE myBI.VENDEDOR(
    idVENDEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    SEXO ENUM('m','f') NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    idGERENTE INT,
    FOREIGN KEY (idGERENTE) REFERENCES myBI.VENDEDOR(idVENDEDOR)
);

-- NOTA_FISCAL(idNOTA_FISCAL,DATA_VENDA,fkCLIENTE,fkVENDEDOR,fkFORMA_PAGAMENTO)
CREATE TABLE myBI.NOTA_FISCAL(
    idNOTA_FISCAL INT AUTO_INCREMENT PRIMARY KEY,
    DATA_VENDA DATETIME NOT NULL,
    fkCLIENTE INT, -- CLIENTE_idCLIENTE
    fkVENDEDOR INT, -- VENDEDOR_idVENDEDOR
    fkFORMA_PAGAMENTO INT, -- FORMA_PAGAMENTO_idFORMA_PAGAMENTO
    FOREIGN KEY (fkCLIENTE) REFERENCES myBI.CLIENTE(idCLIENTE),
    FOREIGN KEY (fkVENDEDOR) REFERENCES myBI.VENDEDOR(idVENDEDOR),
    FOREIGN KEY (fkFORMA_PAGAMENTO) REFERENCES myBI.FORMA_PAGAMENTO(idFORMA_PAGAMENTO)
);

-- ITEM_NOTA(idITEM_NOTA,QUANTIDADE,TOTAL,fkPRODUTO,fkNOTA_FISCAL)
CREATE TABLE myBI.ITEM_NOTA(
    idITEM_NOTA INT AUTO_INCREMENT PRIMARY KEY,
    QUANTIDADE DECIMAL NOT NULL,
    TOTAL DECIMAL NOT NULL,
    fkPRODUTO INT, -- PRODUTO_idPRODUTO
    fkNOTA_FISCAL INT, -- NOTA_FISCAL_idNOTA_FISCAL
    FOREIGN KEY (fkPRODUTO) REFERENCES myBI.PRODUTO(idPRODUTO),
    FOREIGN KEY (fkNOTA_FISCAL) REFERENCES myBI.NOTA_FISCAL(idNOTA_FISCAL)
);
