USE MYBI;

INSERT INTO CATEGORIA VALUES
(1,'LIVROS'),
(2,'DVDS'),
(3,'GAMES'),
(4,'CELULARES'),
(5,'INFORMATICA'),
(6,'TV E AUDIO'),
(7,'ELETRODOMESTICOS'),
(8,'MOVEIS'),
(9,'PASSAGENS');

SELECT * FROM CATEGORIA